### PR TITLE
translation depending on rotational velocity

### PR DESCRIPTION
**Pull request by dettmann**

### CODE REVIEW

**Comment by jmachowinski** [comment]
This is just wrong

**Comment by dettmann** [comment]
Nice comment, it really helps a lot!

In my application, it would be insane to go full speed when turning is requried. The more you need to turn, the less forward speed is desired. So please give me a solution for that

**Comment by jmachowinski** [comment]
Sorry, for the comment, I wanted to update it in the evening and forgot about it...

By modifing the translation speed in this way, you also 
modify the computed curve motion. This leeds to the fact
that the robot will drive on a wrong radius. Actually the line above,
where the max rotation is capped, is wrong as well. 

To do this correct, compute back the curve radius that is wanted, and compute
forward from this a wanted translation and rotation.

Alternatively, set the speed in the motion planner (pretty sure entern supported this)
and use lower speeds for curves.

**Comment by dettmann** [comment]
> Sorry, for the comment, I wanted to update it in the evening and forgot about it...
> 
> By modifing the translation speed in this way, you also
> modify the computed curve motion. This leeds to the fact
> that the robot will drive on a wrong radius. Actually the line above,
> where the max rotation is capped, is wrong as well.
>

Well, the purpose of the follower is to adapt the given translation and angular velocity, thus changing the curve motion, in order to compensate for external disturbances. I see the point, that a given curve cannot be traversed with the desired translation, but this is not a problem in my application. The robot will still stay closed enough to the given trajectory. And if this is a problem, then you simply do not set angular velocity boundaries.

> To do this correct, compute back the curve radius that is wanted, and compute
> forward from this a wanted translation and rotation.

That is possible, but requires some more computations which is not needed, because the follower is already a reactive controller, that modulates the curve in arbitrary way. So, at its outputs are not really true wanted values. At the end, in both ways, tuning of the controller gains has more influence. 

> Alternatively, set the speed in the motion planner (pretty sure entern supported this)
> and use lower speeds for curves.

This would demand much more expert knowledge in the planner and will still not solve the problem when the robot cannot execute the plan due to external disturbances.

**Comment by ajishbabu** [comment]
I agree with @jmachowinski that the solution is not ideal for the following reason
- the controllers are designed with a constant forward velocity in mind. It adapts only the turn velocity depending on the errors.
- If you keep changing the forward velocity, the controller error might not converge (at least in theory). 

Hence, I would suggest a different solution
- sample a bit of your forward path where the curvatures are pretty much similar and for this segment set a constant positive forward velocity. 
- try to use long enough segments of constant velocities so that the errors are able to converge to zero.

I hope this helps!

**Comment by ajishbabu** [comment]
@dettmann  If the method is working and is tested, it should be okay to merge. But make sure that the config value `translationDependentOnRotationalVelocity` is set to false by default, so that no one is affected by an update.

**Comment by jmachowinski** [comment]
> Well, the purpose of the follower is to adapt the given translation and angular velocity, thus changing the curve motion, in order to compensate for external disturbances. I see the point, that a given curve cannot be traversed with the desired translation, but this is not a problem in my application. The robot will still stay closed enough to the given trajectory. And if this is a problem, then you simply do not set angular velocity boundaries.
> 
To do this, is computes a curve motion, that leads back to the wanted trajectory. 
If you change only the translation part, you modify the radius of the curve outputted 
by the the TR Follower (not the input one). This will lead to worse tracking.
You basically create a non linearity here wich is bad.

> > To do this correct, compute back the curve radius that is wanted, and compute
> > forward from this a wanted translation and rotation.
> 
> That is possible, but requires some more computations which is not needed, because the follower is already a reactive controller, that modulates the curve in arbitrary way. So, at its outputs are not really true wanted values. At the end, in both ways, tuning of the controller gains has more influence.
> 
The output of the controller is 100% defined. It can be completely converted to a 
curve radius and a traverse speed on the curve. 
A good example for this is the Artemis robot, if you give a steady rotation and translation, it will
drive almost exactly on the corresponding circle.

Proper scaling of this rotation and translation value is computational trivial and will create almost no overhead. 

> > Alternatively, set the speed in the motion planner (pretty sure entern supported this)
> > and use lower speeds for curves.
> 
> This would demand much more expert knowledge in the planner and will still not solve the problem when the robot cannot execute the plan due to external disturbances.

This will solve the problem in the first place. At the moment it looks like you planner is giving you a
trajectory, which could not be traversed by your robot even if there were no external disturbances.

**Comment by dettmann** [comment]
> > Well, the purpose of the follower is to adapt the given translation and angular velocity, thus changing the curve motion, in order to compensate for external disturbances. I see the point, that a given curve cannot be traversed with the desired translation, but this is not a problem in my application. The robot will still stay closed enough to the given trajectory. And if this is a problem, then you simply do not set angular velocity boundaries.
> 
> To do this, is computes a curve motion, that leads back to the wanted trajectory.
> If you change only the translation part, you modify the radius of the curve outputted
> by the the TR Follower (not the input one). This will lead to worse tracking.
> You basically create a non linearity here wich is bad.
> 
> > > To do this correct, compute back the curve radius that is wanted, and compute
> > > forward from this a wanted translation and rotation.
> > 
> > 
> > That is possible, but requires some more computations which is not needed, because the follower is already a reactive controller, that modulates the curve in arbitrary way. So, at its outputs are not really true wanted values. At the end, in both ways, tuning of the controller gains has more influence.
> 
> The output of the controller is 100% defined. It can be completely converted to a
> curve radius and a traverse speed on the curve.
> A good example for this is the Artemis robot, if you give a steady rotation and translation, it will
> drive almost exactly on the corresponding circle.
> 
> Proper scaling of this rotation and translation value is computational trivial and will create almost no overhead.
> 

The created curve of the follower is defined by the translation and angular velocity. If your robot cannot keep the translation when rotating, the only possibility to preserve the curvature, is to reduce translation and angular velocity simultaneously, ending up in a very slow robot.


> > > Alternatively, set the speed in the motion planner (pretty sure entern supported this)
> > > and use lower speeds for curves.
> > 
> > 
> > This would demand much more expert knowledge in the planner and will still not solve the problem when the robot cannot execute the plan due to external disturbances.
> 
> This will solve the problem in the first place. At the moment it looks like you planner is giving you a
> trajectory, which could not be traversed by your robot even if there were no external disturbances.

You got it! The robot cannot walk with full speed through curves. But if you want to model that in the planner fully correctly, you need to model each different type of robot, consider its joint limits, consider different terrain types, maybe keep the load of the robot in mind, energy level, current posture, ... principally everything that effects the mobility capability. 

So, maybe you're right, we leave the follower without this little feature that gives me almost tracable commands and I'll put this functionality in every receiving motion command interface, where I need it (which creates at the end the same behavior)

**Comment by jmachowinski** [comment]
> The created curve of the follower is defined by the translation and angular velocity. If your robot cannot keep the translation when rotating, the only possibility to preserve the curvature, is to reduce translation and angular velocity simultaneously, ending up in a very slow robot.
> 
Sounds correct to me, sadly my car can't drive a 90 degree turn with 50 km/h either ;-)
If you cap the minimum translation speed, it should result in a neat motion.

> You got it! The robot cannot walk with full speed through curves. But if you want to model that in the planner fully correctly, you need to model each different type of robot, consider its joint limits, consider different terrain types, maybe keep the load of the robot in mind, energy level, current posture, ... principally everything that effects the mobility capability.
> 
The planning-motion_planning_libraries  does this in a simpler way. You define the boundaries of you robot by turn speed etc. From this a set of valid motion primitives are generated, that are used for
path planning. The planner assumes a flat ground here, and makes the assumption, that it will work for any ground. Even if this is not totally accurate, it still results in a better approximation if not taking the limits of the robot into account. If I remember correct, entern had an addition to define a speed per curvature, that was passed on in the trajectory. 

> So, maybe you're right, we leave the follower without this little feature that gives me almost tracable commands and I'll put this functionality in every receiving motion command interface, where I need it (which creates at the end the same behavior)

You got me wrong here, scaling the speed sounds like a sane idea in the tr follower. 
All I am saying is, scale it, while keeping the curvature in mind. Else you will likely 
create further problems down the road. 

Apart from this, the motion controller should try to fullfill the given command as close as possible,
this makes the parameter tuning simpler in the long run.

**Pull request closed without merging**
