### PR TITLE
Changes made in project ENTERN

### PR DESCRIPTION
**Pull request by arneboe**
The trajectory_follower has been heavily modified in project entern.
Since the changes are pretty extreme I would like to use this PR to discuss if and how parts or all of the changes could be merged back into upstream.

@chhtz I guess you are the only one who really knowns what has been changed and why. Any ideas how to merge this?

### CODE REVIEW

**Comment by chhtz** [comment]
Well, I think this was mostly clean-up/simplifications and bug-fixing (and some added features, like `SubTrajectory`, which was actually done by you).

**Comment by arneboe** [comment]
I fixed something in the SubTrajectory but didn't add it. 
I am not sure the SubTrajectory should be inside the trajectory_follower at all. 
A clone of the SubTrajectory exists in control/dwa...
Probably it's best to just remove it or extract it to base-types?

**Comment by chhtz** [comment]
Ok, you added things **into** `SubTrajectory`. I have no idea if removing it from here breaks anything, but I agree that having it here and in `control/dwa` is a bad idea. (In `control/dwa` it is in the global namespace, which does not look like a good idea either. And these types don't look compatible -- or were they before your changes?)

**Comment by ajishbabu** [comment]
Hi @arneboe, @chhtz, 
are you guys actively using the trajectory follower? If so could you take care of the pull request and further maintenance of the repo. I currently do not use it and I will not be able to test it.

**Comment by chhtz** [comment]
I don't have write access on this repo (and I'm not sure if I'll work with this in the near future). @ajishbabu I think this PR can be merged as it is -- cleaning up (like migrating `SubTrajectory` to base-types) could be done independently. 

And if @skasperski is fine with that, I suggest giving him write access to this repo.

**Comment by ajishbabu** [comment]
@skasperski can you take over the maintenance of the repo?

**Comment by skasperski** [comment]
I already have, as i seem to be in the rock-control group. So if no one objects I will merge this.

**Pull request merged**
